include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # print is useful for examples
    avoid_print: false

    # win32 parity requires SCREAMING_CAPS constants
    constant_identifier_names: false  

    # deliberately name generated files after their COM equivalents
    file_names: false

    # doesn't make sense if adjacent strings are not human language
    missing_whitespace_between_adjacent_strings: false

    # Win32 parity requires TitleCase method names
    non_constant_identifier_names: false

    # Some additional lints we want to enforce
    omit_local_variable_types: true
    prefer_expression_function_bodies: true
    prefer_interpolation_to_compose_strings: true
    prefer_relative_imports: true
    unnecessary_lambdas: true